// Code generated by protoc-gen-entgrpc. DO NOT EDIT.
package entpb

import (
	context "context"
	base64 "encoding/base64"
	entproto "entgo.io/contrib/entproto"
	fmt "fmt"
	uuid "github.com/google/uuid"
	ent "github.com/longgggwwww/hrm-ms-permission/ent"
	perm "github.com/longgggwwww/hrm-ms-permission/ent/perm"
	permgroup "github.com/longgggwwww/hrm-ms-permission/ent/permgroup"
	role "github.com/longgggwwww/hrm-ms-permission/ent/role"
	userperm "github.com/longgggwwww/hrm-ms-permission/ent/userperm"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// PermService implements PermServiceServer
type PermService struct {
	client *ent.Client
	UnimplementedPermServiceServer
}

// NewPermService returns a new PermService
func NewPermService(client *ent.Client) *PermService {
	return &PermService{
		client: client,
	}
}

// toProtoPerm transforms the ent type to the pb type
func toProtoPerm(e *ent.Perm) (*Perm, error) {
	v := &Perm{}
	code := e.Code
	v.Code = code
	description := wrapperspb.String(e.Description)
	v.Description = description
	id, err := e.ID.MarshalBinary()
	if err != nil {
		return nil, err
	}
	v.Id = id
	name := e.Name
	v.Name = name
	if edg := e.Edges.Group; edg != nil {
		id, err := edg.ID.MarshalBinary()
		if err != nil {
			return nil, err
		}
		v.Group = &PermGroup{
			Id: id,
		}
	}
	for _, edg := range e.Edges.Roles {
		id, err := edg.ID.MarshalBinary()
		if err != nil {
			return nil, err
		}
		v.Roles = append(v.Roles, &Role{
			Id: id,
		})
	}
	for _, edg := range e.Edges.UserPerms {
		id, err := edg.ID.MarshalBinary()
		if err != nil {
			return nil, err
		}
		v.UserPerms = append(v.UserPerms, &UserPerm{
			Id: id,
		})
	}
	return v, nil
}

// toProtoPermList transforms a list of ent type to a list of pb type
func toProtoPermList(e []*ent.Perm) ([]*Perm, error) {
	var pbList []*Perm
	for _, entEntity := range e {
		pbEntity, err := toProtoPerm(entEntity)
		if err != nil {
			return nil, status.Errorf(codes.Internal, "internal error: %s", err)
		}
		pbList = append(pbList, pbEntity)
	}
	return pbList, nil
}

// Get implements PermServiceServer.Get
func (svc *PermService) Get(ctx context.Context, req *GetPermRequest) (*Perm, error) {
	var (
		err error
		get *ent.Perm
	)
	var id uuid.UUID
	if err := (&id).UnmarshalBinary(req.GetId()); err != nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid argument: %s", err)
	}
	switch req.GetView() {
	case GetPermRequest_VIEW_UNSPECIFIED, GetPermRequest_BASIC:
		get, err = svc.client.Perm.Get(ctx, id)
	case GetPermRequest_WITH_EDGE_IDS:
		get, err = svc.client.Perm.Query().
			Where(perm.ID(id)).
			WithGroup(func(query *ent.PermGroupQuery) {
				query.Select(permgroup.FieldID)
			}).
			WithRoles(func(query *ent.RoleQuery) {
				query.Select(role.FieldID)
			}).
			WithUserPerms(func(query *ent.UserPermQuery) {
				query.Select(userperm.FieldID)
			}).
			Only(ctx)
	default:
		return nil, status.Error(codes.InvalidArgument, "invalid argument: unknown view")
	}
	switch {
	case err == nil:
		return toProtoPerm(get)
	case ent.IsNotFound(err):
		return nil, status.Errorf(codes.NotFound, "not found: %s", err)
	default:
		return nil, status.Errorf(codes.Internal, "internal error: %s", err)
	}

}

// List implements PermServiceServer.List
func (svc *PermService) List(ctx context.Context, req *ListPermRequest) (*ListPermResponse, error) {
	var (
		err      error
		entList  []*ent.Perm
		pageSize int
	)
	pageSize = int(req.GetPageSize())
	switch {
	case pageSize < 0:
		return nil, status.Errorf(codes.InvalidArgument, "page size cannot be less than zero")
	case pageSize == 0 || pageSize > entproto.MaxPageSize:
		pageSize = entproto.MaxPageSize
	}
	listQuery := svc.client.Perm.Query().
		Order(ent.Desc(perm.FieldID)).
		Limit(pageSize + 1)
	if req.GetPageToken() != "" {
		bytes, err := base64.StdEncoding.DecodeString(req.PageToken)
		if err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "page token is invalid")
		}
		pageToken, err := uuid.ParseBytes(bytes)
		if err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "page token is invalid")
		}
		listQuery = listQuery.
			Where(perm.IDLTE(pageToken))
	}
	switch req.GetView() {
	case ListPermRequest_VIEW_UNSPECIFIED, ListPermRequest_BASIC:
		entList, err = listQuery.All(ctx)
	case ListPermRequest_WITH_EDGE_IDS:
		entList, err = listQuery.
			WithGroup(func(query *ent.PermGroupQuery) {
				query.Select(permgroup.FieldID)
			}).
			WithRoles(func(query *ent.RoleQuery) {
				query.Select(role.FieldID)
			}).
			WithUserPerms(func(query *ent.UserPermQuery) {
				query.Select(userperm.FieldID)
			}).
			All(ctx)
	}
	switch {
	case err == nil:
		var nextPageToken string
		if len(entList) == pageSize+1 {
			nextPageToken = base64.StdEncoding.EncodeToString(
				[]byte(fmt.Sprintf("%v", entList[len(entList)-1].ID)))
			entList = entList[:len(entList)-1]
		}
		protoList, err := toProtoPermList(entList)
		if err != nil {
			return nil, status.Errorf(codes.Internal, "internal error: %s", err)
		}
		return &ListPermResponse{
			PermList:      protoList,
			NextPageToken: nextPageToken,
		}, nil
	default:
		return nil, status.Errorf(codes.Internal, "internal error: %s", err)
	}

}
