// Code generated by protoc-gen-entgrpc. DO NOT EDIT.
package entpb

import (
	context "context"
	base64 "encoding/base64"
	entproto "entgo.io/contrib/entproto"
	sqlgraph "entgo.io/ent/dialect/sql/sqlgraph"
	fmt "fmt"
	uuid "github.com/google/uuid"
	ent "github.com/longgggwwww/hrm-ms-permission/ent"
	perm "github.com/longgggwwww/hrm-ms-permission/ent/perm"
	permgroup "github.com/longgggwwww/hrm-ms-permission/ent/permgroup"
	role "github.com/longgggwwww/hrm-ms-permission/ent/role"
	userperm "github.com/longgggwwww/hrm-ms-permission/ent/userperm"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// PermService implements PermServiceServer
type PermService struct {
	client *ent.Client
	UnimplementedPermServiceServer
}

// NewPermService returns a new PermService
func NewPermService(client *ent.Client) *PermService {
	return &PermService{
		client: client,
	}
}

// toProtoPerm transforms the ent type to the pb type
func toProtoPerm(e *ent.Perm) (*Perm, error) {
	v := &Perm{}
	code := e.Code
	v.Code = code
	description := wrapperspb.String(e.Description)
	v.Description = description
	id, err := e.ID.MarshalBinary()
	if err != nil {
		return nil, err
	}
	v.Id = id
	name := e.Name
	v.Name = name
	if edg := e.Edges.Group; edg != nil {
		id, err := edg.ID.MarshalBinary()
		if err != nil {
			return nil, err
		}
		v.Group = &PermGroup{
			Id: id,
		}
	}
	for _, edg := range e.Edges.Roles {
		id, err := edg.ID.MarshalBinary()
		if err != nil {
			return nil, err
		}
		v.Roles = append(v.Roles, &Role{
			Id: id,
		})
	}
	for _, edg := range e.Edges.UserPerms {
		id := int64(edg.ID)
		v.UserPerms = append(v.UserPerms, &UserPerm{
			Id: id,
		})
	}
	return v, nil
}

// toProtoPermList transforms a list of ent type to a list of pb type
func toProtoPermList(e []*ent.Perm) ([]*Perm, error) {
	var pbList []*Perm
	for _, entEntity := range e {
		pbEntity, err := toProtoPerm(entEntity)
		if err != nil {
			return nil, status.Errorf(codes.Internal, "internal error: %s", err)
		}
		pbList = append(pbList, pbEntity)
	}
	return pbList, nil
}

// Create implements PermServiceServer.Create
func (svc *PermService) Create(ctx context.Context, req *CreatePermRequest) (*Perm, error) {
	perm := req.GetPerm()
	m, err := svc.createBuilder(perm)
	if err != nil {
		return nil, err
	}
	res, err := m.Save(ctx)
	switch {
	case err == nil:
		proto, err := toProtoPerm(res)
		if err != nil {
			return nil, status.Errorf(codes.Internal, "internal error: %s", err)
		}
		return proto, nil
	case sqlgraph.IsUniqueConstraintError(err):
		return nil, status.Errorf(codes.AlreadyExists, "already exists: %s", err)
	case ent.IsConstraintError(err):
		return nil, status.Errorf(codes.InvalidArgument, "invalid argument: %s", err)
	default:
		return nil, status.Errorf(codes.Internal, "internal error: %s", err)
	}

}

// Get implements PermServiceServer.Get
func (svc *PermService) Get(ctx context.Context, req *GetPermRequest) (*Perm, error) {
	var (
		err error
		get *ent.Perm
	)
	var id uuid.UUID
	if err := (&id).UnmarshalBinary(req.GetId()); err != nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid argument: %s", err)
	}
	switch req.GetView() {
	case GetPermRequest_VIEW_UNSPECIFIED, GetPermRequest_BASIC:
		get, err = svc.client.Perm.Get(ctx, id)
	case GetPermRequest_WITH_EDGE_IDS:
		get, err = svc.client.Perm.Query().
			Where(perm.ID(id)).
			WithGroup(func(query *ent.PermGroupQuery) {
				query.Select(permgroup.FieldID)
			}).
			WithRoles(func(query *ent.RoleQuery) {
				query.Select(role.FieldID)
			}).
			WithUserPerms(func(query *ent.UserPermQuery) {
				query.Select(userperm.FieldID)
			}).
			Only(ctx)
	default:
		return nil, status.Error(codes.InvalidArgument, "invalid argument: unknown view")
	}
	switch {
	case err == nil:
		return toProtoPerm(get)
	case ent.IsNotFound(err):
		return nil, status.Errorf(codes.NotFound, "not found: %s", err)
	default:
		return nil, status.Errorf(codes.Internal, "internal error: %s", err)
	}

}

// Update implements PermServiceServer.Update
func (svc *PermService) Update(ctx context.Context, req *UpdatePermRequest) (*Perm, error) {
	perm := req.GetPerm()
	var permID uuid.UUID
	if err := (&permID).UnmarshalBinary(perm.GetId()); err != nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid argument: %s", err)
	}
	m := svc.client.Perm.UpdateOneID(permID)
	permCode := perm.GetCode()
	m.SetCode(permCode)
	if perm.GetDescription() != nil {
		permDescription := perm.GetDescription().GetValue()
		m.SetDescription(permDescription)
	}
	permName := perm.GetName()
	m.SetName(permName)
	if perm.GetGroup() != nil {
		var permGroup uuid.UUID
		if err := (&permGroup).UnmarshalBinary(perm.GetGroup().GetId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "invalid argument: %s", err)
		}
		m.SetGroupID(permGroup)
	}
	for _, item := range perm.GetRoles() {
		var roles uuid.UUID
		if err := (&roles).UnmarshalBinary(item.GetId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "invalid argument: %s", err)
		}
		m.AddRoleIDs(roles)
	}
	for _, item := range perm.GetUserPerms() {
		userperms := int(item.GetId())
		m.AddUserPermIDs(userperms)
	}

	res, err := m.Save(ctx)
	switch {
	case err == nil:
		proto, err := toProtoPerm(res)
		if err != nil {
			return nil, status.Errorf(codes.Internal, "internal error: %s", err)
		}
		return proto, nil
	case sqlgraph.IsUniqueConstraintError(err):
		return nil, status.Errorf(codes.AlreadyExists, "already exists: %s", err)
	case ent.IsConstraintError(err):
		return nil, status.Errorf(codes.InvalidArgument, "invalid argument: %s", err)
	default:
		return nil, status.Errorf(codes.Internal, "internal error: %s", err)
	}

}

// Delete implements PermServiceServer.Delete
func (svc *PermService) Delete(ctx context.Context, req *DeletePermRequest) (*emptypb.Empty, error) {
	var err error
	var id uuid.UUID
	if err := (&id).UnmarshalBinary(req.GetId()); err != nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid argument: %s", err)
	}
	err = svc.client.Perm.DeleteOneID(id).Exec(ctx)
	switch {
	case err == nil:
		return &emptypb.Empty{}, nil
	case ent.IsNotFound(err):
		return nil, status.Errorf(codes.NotFound, "not found: %s", err)
	default:
		return nil, status.Errorf(codes.Internal, "internal error: %s", err)
	}

}

// List implements PermServiceServer.List
func (svc *PermService) List(ctx context.Context, req *ListPermRequest) (*ListPermResponse, error) {
	var (
		err      error
		entList  []*ent.Perm
		pageSize int
	)
	pageSize = int(req.GetPageSize())
	switch {
	case pageSize < 0:
		return nil, status.Errorf(codes.InvalidArgument, "page size cannot be less than zero")
	case pageSize == 0 || pageSize > entproto.MaxPageSize:
		pageSize = entproto.MaxPageSize
	}
	listQuery := svc.client.Perm.Query().
		Order(ent.Desc(perm.FieldID)).
		Limit(pageSize + 1)
	if req.GetPageToken() != "" {
		bytes, err := base64.StdEncoding.DecodeString(req.PageToken)
		if err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "page token is invalid")
		}
		pageToken, err := uuid.ParseBytes(bytes)
		if err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "page token is invalid")
		}
		listQuery = listQuery.
			Where(perm.IDLTE(pageToken))
	}
	switch req.GetView() {
	case ListPermRequest_VIEW_UNSPECIFIED, ListPermRequest_BASIC:
		entList, err = listQuery.All(ctx)
	case ListPermRequest_WITH_EDGE_IDS:
		entList, err = listQuery.
			WithGroup(func(query *ent.PermGroupQuery) {
				query.Select(permgroup.FieldID)
			}).
			WithRoles(func(query *ent.RoleQuery) {
				query.Select(role.FieldID)
			}).
			WithUserPerms(func(query *ent.UserPermQuery) {
				query.Select(userperm.FieldID)
			}).
			All(ctx)
	}
	switch {
	case err == nil:
		var nextPageToken string
		if len(entList) == pageSize+1 {
			nextPageToken = base64.StdEncoding.EncodeToString(
				[]byte(fmt.Sprintf("%v", entList[len(entList)-1].ID)))
			entList = entList[:len(entList)-1]
		}
		protoList, err := toProtoPermList(entList)
		if err != nil {
			return nil, status.Errorf(codes.Internal, "internal error: %s", err)
		}
		return &ListPermResponse{
			PermList:      protoList,
			NextPageToken: nextPageToken,
		}, nil
	default:
		return nil, status.Errorf(codes.Internal, "internal error: %s", err)
	}

}

// BatchCreate implements PermServiceServer.BatchCreate
func (svc *PermService) BatchCreate(ctx context.Context, req *BatchCreatePermsRequest) (*BatchCreatePermsResponse, error) {
	requests := req.GetRequests()
	if len(requests) > entproto.MaxBatchCreateSize {
		return nil, status.Errorf(codes.InvalidArgument, "batch size cannot be greater than %d", entproto.MaxBatchCreateSize)
	}
	bulk := make([]*ent.PermCreate, len(requests))
	for i, req := range requests {
		perm := req.GetPerm()
		var err error
		bulk[i], err = svc.createBuilder(perm)
		if err != nil {
			return nil, err
		}
	}
	res, err := svc.client.Perm.CreateBulk(bulk...).Save(ctx)
	switch {
	case err == nil:
		protoList, err := toProtoPermList(res)
		if err != nil {
			return nil, status.Errorf(codes.Internal, "internal error: %s", err)
		}
		return &BatchCreatePermsResponse{
			Perms: protoList,
		}, nil
	case sqlgraph.IsUniqueConstraintError(err):
		return nil, status.Errorf(codes.AlreadyExists, "already exists: %s", err)
	case ent.IsConstraintError(err):
		return nil, status.Errorf(codes.InvalidArgument, "invalid argument: %s", err)
	default:
		return nil, status.Errorf(codes.Internal, "internal error: %s", err)
	}

}

func (svc *PermService) createBuilder(perm *Perm) (*ent.PermCreate, error) {
	m := svc.client.Perm.Create()
	permCode := perm.GetCode()
	m.SetCode(permCode)
	if perm.GetDescription() != nil {
		permDescription := perm.GetDescription().GetValue()
		m.SetDescription(permDescription)
	}
	permName := perm.GetName()
	m.SetName(permName)
	if perm.GetGroup() != nil {
		var permGroup uuid.UUID
		if err := (&permGroup).UnmarshalBinary(perm.GetGroup().GetId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "invalid argument: %s", err)
		}
		m.SetGroupID(permGroup)
	}
	for _, item := range perm.GetRoles() {
		var roles uuid.UUID
		if err := (&roles).UnmarshalBinary(item.GetId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "invalid argument: %s", err)
		}
		m.AddRoleIDs(roles)
	}
	for _, item := range perm.GetUserPerms() {
		userperms := int(item.GetId())
		m.AddUserPermIDs(userperms)
	}
	return m, nil
}
