// Code generated by entproto. DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: entpb/entpb.proto

package entpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPermRequest_View int32

const (
	GetPermRequest_VIEW_UNSPECIFIED GetPermRequest_View = 0
	GetPermRequest_BASIC            GetPermRequest_View = 1
	GetPermRequest_WITH_EDGE_IDS    GetPermRequest_View = 2
)

// Enum value maps for GetPermRequest_View.
var (
	GetPermRequest_View_name = map[int32]string{
		0: "VIEW_UNSPECIFIED",
		1: "BASIC",
		2: "WITH_EDGE_IDS",
	}
	GetPermRequest_View_value = map[string]int32{
		"VIEW_UNSPECIFIED": 0,
		"BASIC":            1,
		"WITH_EDGE_IDS":    2,
	}
)

func (x GetPermRequest_View) Enum() *GetPermRequest_View {
	p := new(GetPermRequest_View)
	*p = x
	return p
}

func (x GetPermRequest_View) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetPermRequest_View) Descriptor() protoreflect.EnumDescriptor {
	return file_entpb_entpb_proto_enumTypes[0].Descriptor()
}

func (GetPermRequest_View) Type() protoreflect.EnumType {
	return &file_entpb_entpb_proto_enumTypes[0]
}

func (x GetPermRequest_View) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetPermRequest_View.Descriptor instead.
func (GetPermRequest_View) EnumDescriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{2, 0}
}

type ListPermRequest_View int32

const (
	ListPermRequest_VIEW_UNSPECIFIED ListPermRequest_View = 0
	ListPermRequest_BASIC            ListPermRequest_View = 1
	ListPermRequest_WITH_EDGE_IDS    ListPermRequest_View = 2
)

// Enum value maps for ListPermRequest_View.
var (
	ListPermRequest_View_name = map[int32]string{
		0: "VIEW_UNSPECIFIED",
		1: "BASIC",
		2: "WITH_EDGE_IDS",
	}
	ListPermRequest_View_value = map[string]int32{
		"VIEW_UNSPECIFIED": 0,
		"BASIC":            1,
		"WITH_EDGE_IDS":    2,
	}
)

func (x ListPermRequest_View) Enum() *ListPermRequest_View {
	p := new(ListPermRequest_View)
	*p = x
	return p
}

func (x ListPermRequest_View) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListPermRequest_View) Descriptor() protoreflect.EnumDescriptor {
	return file_entpb_entpb_proto_enumTypes[1].Descriptor()
}

func (ListPermRequest_View) Type() protoreflect.EnumType {
	return &file_entpb_entpb_proto_enumTypes[1]
}

func (x ListPermRequest_View) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListPermRequest_View.Descriptor instead.
func (ListPermRequest_View) EnumDescriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{5, 0}
}

type GetPermGroupRequest_View int32

const (
	GetPermGroupRequest_VIEW_UNSPECIFIED GetPermGroupRequest_View = 0
	GetPermGroupRequest_BASIC            GetPermGroupRequest_View = 1
	GetPermGroupRequest_WITH_EDGE_IDS    GetPermGroupRequest_View = 2
)

// Enum value maps for GetPermGroupRequest_View.
var (
	GetPermGroupRequest_View_name = map[int32]string{
		0: "VIEW_UNSPECIFIED",
		1: "BASIC",
		2: "WITH_EDGE_IDS",
	}
	GetPermGroupRequest_View_value = map[string]int32{
		"VIEW_UNSPECIFIED": 0,
		"BASIC":            1,
		"WITH_EDGE_IDS":    2,
	}
)

func (x GetPermGroupRequest_View) Enum() *GetPermGroupRequest_View {
	p := new(GetPermGroupRequest_View)
	*p = x
	return p
}

func (x GetPermGroupRequest_View) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetPermGroupRequest_View) Descriptor() protoreflect.EnumDescriptor {
	return file_entpb_entpb_proto_enumTypes[2].Descriptor()
}

func (GetPermGroupRequest_View) Type() protoreflect.EnumType {
	return &file_entpb_entpb_proto_enumTypes[2]
}

func (x GetPermGroupRequest_View) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetPermGroupRequest_View.Descriptor instead.
func (GetPermGroupRequest_View) EnumDescriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{11, 0}
}

type ListPermGroupRequest_View int32

const (
	ListPermGroupRequest_VIEW_UNSPECIFIED ListPermGroupRequest_View = 0
	ListPermGroupRequest_BASIC            ListPermGroupRequest_View = 1
	ListPermGroupRequest_WITH_EDGE_IDS    ListPermGroupRequest_View = 2
)

// Enum value maps for ListPermGroupRequest_View.
var (
	ListPermGroupRequest_View_name = map[int32]string{
		0: "VIEW_UNSPECIFIED",
		1: "BASIC",
		2: "WITH_EDGE_IDS",
	}
	ListPermGroupRequest_View_value = map[string]int32{
		"VIEW_UNSPECIFIED": 0,
		"BASIC":            1,
		"WITH_EDGE_IDS":    2,
	}
)

func (x ListPermGroupRequest_View) Enum() *ListPermGroupRequest_View {
	p := new(ListPermGroupRequest_View)
	*p = x
	return p
}

func (x ListPermGroupRequest_View) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListPermGroupRequest_View) Descriptor() protoreflect.EnumDescriptor {
	return file_entpb_entpb_proto_enumTypes[3].Descriptor()
}

func (ListPermGroupRequest_View) Type() protoreflect.EnumType {
	return &file_entpb_entpb_proto_enumTypes[3]
}

func (x ListPermGroupRequest_View) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListPermGroupRequest_View.Descriptor instead.
func (ListPermGroupRequest_View) EnumDescriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{14, 0}
}

type GetRoleRequest_View int32

const (
	GetRoleRequest_VIEW_UNSPECIFIED GetRoleRequest_View = 0
	GetRoleRequest_BASIC            GetRoleRequest_View = 1
	GetRoleRequest_WITH_EDGE_IDS    GetRoleRequest_View = 2
)

// Enum value maps for GetRoleRequest_View.
var (
	GetRoleRequest_View_name = map[int32]string{
		0: "VIEW_UNSPECIFIED",
		1: "BASIC",
		2: "WITH_EDGE_IDS",
	}
	GetRoleRequest_View_value = map[string]int32{
		"VIEW_UNSPECIFIED": 0,
		"BASIC":            1,
		"WITH_EDGE_IDS":    2,
	}
)

func (x GetRoleRequest_View) Enum() *GetRoleRequest_View {
	p := new(GetRoleRequest_View)
	*p = x
	return p
}

func (x GetRoleRequest_View) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetRoleRequest_View) Descriptor() protoreflect.EnumDescriptor {
	return file_entpb_entpb_proto_enumTypes[4].Descriptor()
}

func (GetRoleRequest_View) Type() protoreflect.EnumType {
	return &file_entpb_entpb_proto_enumTypes[4]
}

func (x GetRoleRequest_View) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetRoleRequest_View.Descriptor instead.
func (GetRoleRequest_View) EnumDescriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{20, 0}
}

type ListRoleRequest_View int32

const (
	ListRoleRequest_VIEW_UNSPECIFIED ListRoleRequest_View = 0
	ListRoleRequest_BASIC            ListRoleRequest_View = 1
	ListRoleRequest_WITH_EDGE_IDS    ListRoleRequest_View = 2
)

// Enum value maps for ListRoleRequest_View.
var (
	ListRoleRequest_View_name = map[int32]string{
		0: "VIEW_UNSPECIFIED",
		1: "BASIC",
		2: "WITH_EDGE_IDS",
	}
	ListRoleRequest_View_value = map[string]int32{
		"VIEW_UNSPECIFIED": 0,
		"BASIC":            1,
		"WITH_EDGE_IDS":    2,
	}
)

func (x ListRoleRequest_View) Enum() *ListRoleRequest_View {
	p := new(ListRoleRequest_View)
	*p = x
	return p
}

func (x ListRoleRequest_View) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListRoleRequest_View) Descriptor() protoreflect.EnumDescriptor {
	return file_entpb_entpb_proto_enumTypes[5].Descriptor()
}

func (ListRoleRequest_View) Type() protoreflect.EnumType {
	return &file_entpb_entpb_proto_enumTypes[5]
}

func (x ListRoleRequest_View) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListRoleRequest_View.Descriptor instead.
func (ListRoleRequest_View) EnumDescriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{23, 0}
}

type Perm struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            int64                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                  `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                  `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Group         *PermGroup              `protobuf:"bytes,5,opt,name=group,proto3" json:"group,omitempty"`
	Roles         []*Role                 `protobuf:"bytes,6,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Perm) Reset() {
	*x = Perm{}
	mi := &file_entpb_entpb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Perm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Perm) ProtoMessage() {}

func (x *Perm) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_entpb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Perm.ProtoReflect.Descriptor instead.
func (*Perm) Descriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{0}
}

func (x *Perm) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Perm) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Perm) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Perm) GetDescription() *wrapperspb.StringValue {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *Perm) GetGroup() *PermGroup {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *Perm) GetRoles() []*Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

type CreatePermRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Perm          *Perm                  `protobuf:"bytes,1,opt,name=perm,proto3" json:"perm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePermRequest) Reset() {
	*x = CreatePermRequest{}
	mi := &file_entpb_entpb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePermRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePermRequest) ProtoMessage() {}

func (x *CreatePermRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_entpb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePermRequest.ProtoReflect.Descriptor instead.
func (*CreatePermRequest) Descriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePermRequest) GetPerm() *Perm {
	if x != nil {
		return x.Perm
	}
	return nil
}

type GetPermRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	View          GetPermRequest_View    `protobuf:"varint,2,opt,name=view,proto3,enum=entpb.GetPermRequest_View" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPermRequest) Reset() {
	*x = GetPermRequest{}
	mi := &file_entpb_entpb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPermRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPermRequest) ProtoMessage() {}

func (x *GetPermRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_entpb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPermRequest.ProtoReflect.Descriptor instead.
func (*GetPermRequest) Descriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{2}
}

func (x *GetPermRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetPermRequest) GetView() GetPermRequest_View {
	if x != nil {
		return x.View
	}
	return GetPermRequest_VIEW_UNSPECIFIED
}

type UpdatePermRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Perm          *Perm                  `protobuf:"bytes,1,opt,name=perm,proto3" json:"perm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePermRequest) Reset() {
	*x = UpdatePermRequest{}
	mi := &file_entpb_entpb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePermRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePermRequest) ProtoMessage() {}

func (x *UpdatePermRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_entpb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePermRequest.ProtoReflect.Descriptor instead.
func (*UpdatePermRequest) Descriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{3}
}

func (x *UpdatePermRequest) GetPerm() *Perm {
	if x != nil {
		return x.Perm
	}
	return nil
}

type DeletePermRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePermRequest) Reset() {
	*x = DeletePermRequest{}
	mi := &file_entpb_entpb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePermRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePermRequest) ProtoMessage() {}

func (x *DeletePermRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_entpb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePermRequest.ProtoReflect.Descriptor instead.
func (*DeletePermRequest) Descriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{4}
}

func (x *DeletePermRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListPermRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	View          ListPermRequest_View   `protobuf:"varint,3,opt,name=view,proto3,enum=entpb.ListPermRequest_View" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermRequest) Reset() {
	*x = ListPermRequest{}
	mi := &file_entpb_entpb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermRequest) ProtoMessage() {}

func (x *ListPermRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_entpb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermRequest.ProtoReflect.Descriptor instead.
func (*ListPermRequest) Descriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{5}
}

func (x *ListPermRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListPermRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListPermRequest) GetView() ListPermRequest_View {
	if x != nil {
		return x.View
	}
	return ListPermRequest_VIEW_UNSPECIFIED
}

type ListPermResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PermList      []*Perm                `protobuf:"bytes,1,rep,name=perm_list,json=permList,proto3" json:"perm_list,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermResponse) Reset() {
	*x = ListPermResponse{}
	mi := &file_entpb_entpb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermResponse) ProtoMessage() {}

func (x *ListPermResponse) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_entpb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermResponse.ProtoReflect.Descriptor instead.
func (*ListPermResponse) Descriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{6}
}

func (x *ListPermResponse) GetPermList() []*Perm {
	if x != nil {
		return x.PermList
	}
	return nil
}

func (x *ListPermResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type BatchCreatePermsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*CreatePermRequest   `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreatePermsRequest) Reset() {
	*x = BatchCreatePermsRequest{}
	mi := &file_entpb_entpb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreatePermsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreatePermsRequest) ProtoMessage() {}

func (x *BatchCreatePermsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_entpb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreatePermsRequest.ProtoReflect.Descriptor instead.
func (*BatchCreatePermsRequest) Descriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{7}
}

func (x *BatchCreatePermsRequest) GetRequests() []*CreatePermRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type BatchCreatePermsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Perms         []*Perm                `protobuf:"bytes,1,rep,name=perms,proto3" json:"perms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreatePermsResponse) Reset() {
	*x = BatchCreatePermsResponse{}
	mi := &file_entpb_entpb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreatePermsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreatePermsResponse) ProtoMessage() {}

func (x *BatchCreatePermsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_entpb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreatePermsResponse.ProtoReflect.Descriptor instead.
func (*BatchCreatePermsResponse) Descriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{8}
}

func (x *BatchCreatePermsResponse) GetPerms() []*Perm {
	if x != nil {
		return x.Perms
	}
	return nil
}

type PermGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Perms         []*Perm                `protobuf:"bytes,4,rep,name=perms,proto3" json:"perms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermGroup) Reset() {
	*x = PermGroup{}
	mi := &file_entpb_entpb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermGroup) ProtoMessage() {}

func (x *PermGroup) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_entpb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermGroup.ProtoReflect.Descriptor instead.
func (*PermGroup) Descriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{9}
}

func (x *PermGroup) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PermGroup) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *PermGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PermGroup) GetPerms() []*Perm {
	if x != nil {
		return x.Perms
	}
	return nil
}

type CreatePermGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PermGroup     *PermGroup             `protobuf:"bytes,1,opt,name=perm_group,json=permGroup,proto3" json:"perm_group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePermGroupRequest) Reset() {
	*x = CreatePermGroupRequest{}
	mi := &file_entpb_entpb_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePermGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePermGroupRequest) ProtoMessage() {}

func (x *CreatePermGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_entpb_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePermGroupRequest.ProtoReflect.Descriptor instead.
func (*CreatePermGroupRequest) Descriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{10}
}

func (x *CreatePermGroupRequest) GetPermGroup() *PermGroup {
	if x != nil {
		return x.PermGroup
	}
	return nil
}

type GetPermGroupRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Id            int64                    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	View          GetPermGroupRequest_View `protobuf:"varint,2,opt,name=view,proto3,enum=entpb.GetPermGroupRequest_View" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPermGroupRequest) Reset() {
	*x = GetPermGroupRequest{}
	mi := &file_entpb_entpb_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPermGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPermGroupRequest) ProtoMessage() {}

func (x *GetPermGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_entpb_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPermGroupRequest.ProtoReflect.Descriptor instead.
func (*GetPermGroupRequest) Descriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{11}
}

func (x *GetPermGroupRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetPermGroupRequest) GetView() GetPermGroupRequest_View {
	if x != nil {
		return x.View
	}
	return GetPermGroupRequest_VIEW_UNSPECIFIED
}

type UpdatePermGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PermGroup     *PermGroup             `protobuf:"bytes,1,opt,name=perm_group,json=permGroup,proto3" json:"perm_group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePermGroupRequest) Reset() {
	*x = UpdatePermGroupRequest{}
	mi := &file_entpb_entpb_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePermGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePermGroupRequest) ProtoMessage() {}

func (x *UpdatePermGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_entpb_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePermGroupRequest.ProtoReflect.Descriptor instead.
func (*UpdatePermGroupRequest) Descriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{12}
}

func (x *UpdatePermGroupRequest) GetPermGroup() *PermGroup {
	if x != nil {
		return x.PermGroup
	}
	return nil
}

type DeletePermGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePermGroupRequest) Reset() {
	*x = DeletePermGroupRequest{}
	mi := &file_entpb_entpb_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePermGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePermGroupRequest) ProtoMessage() {}

func (x *DeletePermGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_entpb_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePermGroupRequest.ProtoReflect.Descriptor instead.
func (*DeletePermGroupRequest) Descriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{13}
}

func (x *DeletePermGroupRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListPermGroupRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	PageSize      int32                     `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                    `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	View          ListPermGroupRequest_View `protobuf:"varint,3,opt,name=view,proto3,enum=entpb.ListPermGroupRequest_View" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermGroupRequest) Reset() {
	*x = ListPermGroupRequest{}
	mi := &file_entpb_entpb_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermGroupRequest) ProtoMessage() {}

func (x *ListPermGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_entpb_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermGroupRequest.ProtoReflect.Descriptor instead.
func (*ListPermGroupRequest) Descriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{14}
}

func (x *ListPermGroupRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListPermGroupRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListPermGroupRequest) GetView() ListPermGroupRequest_View {
	if x != nil {
		return x.View
	}
	return ListPermGroupRequest_VIEW_UNSPECIFIED
}

type ListPermGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PermGroupList []*PermGroup           `protobuf:"bytes,1,rep,name=perm_group_list,json=permGroupList,proto3" json:"perm_group_list,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermGroupResponse) Reset() {
	*x = ListPermGroupResponse{}
	mi := &file_entpb_entpb_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermGroupResponse) ProtoMessage() {}

func (x *ListPermGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_entpb_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermGroupResponse.ProtoReflect.Descriptor instead.
func (*ListPermGroupResponse) Descriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{15}
}

func (x *ListPermGroupResponse) GetPermGroupList() []*PermGroup {
	if x != nil {
		return x.PermGroupList
	}
	return nil
}

func (x *ListPermGroupResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type BatchCreatePermGroupsRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Requests      []*CreatePermGroupRequest `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreatePermGroupsRequest) Reset() {
	*x = BatchCreatePermGroupsRequest{}
	mi := &file_entpb_entpb_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreatePermGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreatePermGroupsRequest) ProtoMessage() {}

func (x *BatchCreatePermGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_entpb_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreatePermGroupsRequest.ProtoReflect.Descriptor instead.
func (*BatchCreatePermGroupsRequest) Descriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{16}
}

func (x *BatchCreatePermGroupsRequest) GetRequests() []*CreatePermGroupRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type BatchCreatePermGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PermGroups    []*PermGroup           `protobuf:"bytes,1,rep,name=perm_groups,json=permGroups,proto3" json:"perm_groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreatePermGroupsResponse) Reset() {
	*x = BatchCreatePermGroupsResponse{}
	mi := &file_entpb_entpb_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreatePermGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreatePermGroupsResponse) ProtoMessage() {}

func (x *BatchCreatePermGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_entpb_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreatePermGroupsResponse.ProtoReflect.Descriptor instead.
func (*BatchCreatePermGroupsResponse) Descriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{17}
}

func (x *BatchCreatePermGroupsResponse) GetPermGroups() []*PermGroup {
	if x != nil {
		return x.PermGroups
	}
	return nil
}

type Role struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            int64                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Color         *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	Description   *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Perms         []*Perm                 `protobuf:"bytes,5,rep,name=perms,proto3" json:"perms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_entpb_entpb_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_entpb_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{18}
}

func (x *Role) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Role) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Role) GetColor() *wrapperspb.StringValue {
	if x != nil {
		return x.Color
	}
	return nil
}

func (x *Role) GetDescription() *wrapperspb.StringValue {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *Role) GetPerms() []*Perm {
	if x != nil {
		return x.Perms
	}
	return nil
}

type CreateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *Role                  `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleRequest) Reset() {
	*x = CreateRoleRequest{}
	mi := &file_entpb_entpb_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleRequest) ProtoMessage() {}

func (x *CreateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_entpb_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleRequest.ProtoReflect.Descriptor instead.
func (*CreateRoleRequest) Descriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{19}
}

func (x *CreateRoleRequest) GetRole() *Role {
	if x != nil {
		return x.Role
	}
	return nil
}

type GetRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	View          GetRoleRequest_View    `protobuf:"varint,2,opt,name=view,proto3,enum=entpb.GetRoleRequest_View" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleRequest) Reset() {
	*x = GetRoleRequest{}
	mi := &file_entpb_entpb_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleRequest) ProtoMessage() {}

func (x *GetRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_entpb_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleRequest.ProtoReflect.Descriptor instead.
func (*GetRoleRequest) Descriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{20}
}

func (x *GetRoleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetRoleRequest) GetView() GetRoleRequest_View {
	if x != nil {
		return x.View
	}
	return GetRoleRequest_VIEW_UNSPECIFIED
}

type UpdateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *Role                  `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleRequest) Reset() {
	*x = UpdateRoleRequest{}
	mi := &file_entpb_entpb_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleRequest) ProtoMessage() {}

func (x *UpdateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_entpb_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoleRequest) Descriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateRoleRequest) GetRole() *Role {
	if x != nil {
		return x.Role
	}
	return nil
}

type DeleteRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleRequest) Reset() {
	*x = DeleteRoleRequest{}
	mi := &file_entpb_entpb_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleRequest) ProtoMessage() {}

func (x *DeleteRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_entpb_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoleRequest) Descriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteRoleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	View          ListRoleRequest_View   `protobuf:"varint,3,opt,name=view,proto3,enum=entpb.ListRoleRequest_View" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoleRequest) Reset() {
	*x = ListRoleRequest{}
	mi := &file_entpb_entpb_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoleRequest) ProtoMessage() {}

func (x *ListRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_entpb_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoleRequest.ProtoReflect.Descriptor instead.
func (*ListRoleRequest) Descriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{23}
}

func (x *ListRoleRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRoleRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListRoleRequest) GetView() ListRoleRequest_View {
	if x != nil {
		return x.View
	}
	return ListRoleRequest_VIEW_UNSPECIFIED
}

type ListRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleList      []*Role                `protobuf:"bytes,1,rep,name=role_list,json=roleList,proto3" json:"role_list,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoleResponse) Reset() {
	*x = ListRoleResponse{}
	mi := &file_entpb_entpb_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoleResponse) ProtoMessage() {}

func (x *ListRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_entpb_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoleResponse.ProtoReflect.Descriptor instead.
func (*ListRoleResponse) Descriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{24}
}

func (x *ListRoleResponse) GetRoleList() []*Role {
	if x != nil {
		return x.RoleList
	}
	return nil
}

func (x *ListRoleResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type BatchCreateRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*CreateRoleRequest   `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateRolesRequest) Reset() {
	*x = BatchCreateRolesRequest{}
	mi := &file_entpb_entpb_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateRolesRequest) ProtoMessage() {}

func (x *BatchCreateRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_entpb_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateRolesRequest.ProtoReflect.Descriptor instead.
func (*BatchCreateRolesRequest) Descriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{25}
}

func (x *BatchCreateRolesRequest) GetRequests() []*CreateRoleRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type BatchCreateRolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []*Role                `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateRolesResponse) Reset() {
	*x = BatchCreateRolesResponse{}
	mi := &file_entpb_entpb_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateRolesResponse) ProtoMessage() {}

func (x *BatchCreateRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_entpb_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateRolesResponse.ProtoReflect.Descriptor instead.
func (*BatchCreateRolesResponse) Descriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{26}
}

func (x *BatchCreateRolesResponse) GetRoles() []*Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

var File_entpb_entpb_proto protoreflect.FileDescriptor

const file_entpb_entpb_proto_rawDesc = "" +
	"\n" +
	"\x11entpb/entpb.proto\x12\x05entpb\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xc9\x01\n" +
	"\x04Perm\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12>\n" +
	"\vdescription\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\vdescription\x12&\n" +
	"\x05group\x18\x05 \x01(\v2\x10.entpb.PermGroupR\x05group\x12!\n" +
	"\x05roles\x18\x06 \x03(\v2\v.entpb.RoleR\x05roles\"4\n" +
	"\x11CreatePermRequest\x12\x1f\n" +
	"\x04perm\x18\x01 \x01(\v2\v.entpb.PermR\x04perm\"\x8c\x01\n" +
	"\x0eGetPermRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12.\n" +
	"\x04view\x18\x02 \x01(\x0e2\x1a.entpb.GetPermRequest.ViewR\x04view\":\n" +
	"\x04View\x12\x14\n" +
	"\x10VIEW_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05BASIC\x10\x01\x12\x11\n" +
	"\rWITH_EDGE_IDS\x10\x02\"4\n" +
	"\x11UpdatePermRequest\x12\x1f\n" +
	"\x04perm\x18\x01 \x01(\v2\v.entpb.PermR\x04perm\"#\n" +
	"\x11DeletePermRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xba\x01\n" +
	"\x0fListPermRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12/\n" +
	"\x04view\x18\x03 \x01(\x0e2\x1b.entpb.ListPermRequest.ViewR\x04view\":\n" +
	"\x04View\x12\x14\n" +
	"\x10VIEW_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05BASIC\x10\x01\x12\x11\n" +
	"\rWITH_EDGE_IDS\x10\x02\"d\n" +
	"\x10ListPermResponse\x12(\n" +
	"\tperm_list\x18\x01 \x03(\v2\v.entpb.PermR\bpermList\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"O\n" +
	"\x17BatchCreatePermsRequest\x124\n" +
	"\brequests\x18\x01 \x03(\v2\x18.entpb.CreatePermRequestR\brequests\"=\n" +
	"\x18BatchCreatePermsResponse\x12!\n" +
	"\x05perms\x18\x01 \x03(\v2\v.entpb.PermR\x05perms\"f\n" +
	"\tPermGroup\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12!\n" +
	"\x05perms\x18\x04 \x03(\v2\v.entpb.PermR\x05perms\"I\n" +
	"\x16CreatePermGroupRequest\x12/\n" +
	"\n" +
	"perm_group\x18\x01 \x01(\v2\x10.entpb.PermGroupR\tpermGroup\"\x96\x01\n" +
	"\x13GetPermGroupRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x123\n" +
	"\x04view\x18\x02 \x01(\x0e2\x1f.entpb.GetPermGroupRequest.ViewR\x04view\":\n" +
	"\x04View\x12\x14\n" +
	"\x10VIEW_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05BASIC\x10\x01\x12\x11\n" +
	"\rWITH_EDGE_IDS\x10\x02\"I\n" +
	"\x16UpdatePermGroupRequest\x12/\n" +
	"\n" +
	"perm_group\x18\x01 \x01(\v2\x10.entpb.PermGroupR\tpermGroup\"(\n" +
	"\x16DeletePermGroupRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xc4\x01\n" +
	"\x14ListPermGroupRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x124\n" +
	"\x04view\x18\x03 \x01(\x0e2 .entpb.ListPermGroupRequest.ViewR\x04view\":\n" +
	"\x04View\x12\x14\n" +
	"\x10VIEW_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05BASIC\x10\x01\x12\x11\n" +
	"\rWITH_EDGE_IDS\x10\x02\"y\n" +
	"\x15ListPermGroupResponse\x128\n" +
	"\x0fperm_group_list\x18\x01 \x03(\v2\x10.entpb.PermGroupR\rpermGroupList\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"Y\n" +
	"\x1cBatchCreatePermGroupsRequest\x129\n" +
	"\brequests\x18\x01 \x03(\v2\x1d.entpb.CreatePermGroupRequestR\brequests\"R\n" +
	"\x1dBatchCreatePermGroupsResponse\x121\n" +
	"\vperm_groups\x18\x01 \x03(\v2\x10.entpb.PermGroupR\n" +
	"permGroups\"\xc1\x01\n" +
	"\x04Role\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x122\n" +
	"\x05color\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\x05color\x12>\n" +
	"\vdescription\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\vdescription\x12!\n" +
	"\x05perms\x18\x05 \x03(\v2\v.entpb.PermR\x05perms\"4\n" +
	"\x11CreateRoleRequest\x12\x1f\n" +
	"\x04role\x18\x01 \x01(\v2\v.entpb.RoleR\x04role\"\x8c\x01\n" +
	"\x0eGetRoleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12.\n" +
	"\x04view\x18\x02 \x01(\x0e2\x1a.entpb.GetRoleRequest.ViewR\x04view\":\n" +
	"\x04View\x12\x14\n" +
	"\x10VIEW_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05BASIC\x10\x01\x12\x11\n" +
	"\rWITH_EDGE_IDS\x10\x02\"4\n" +
	"\x11UpdateRoleRequest\x12\x1f\n" +
	"\x04role\x18\x01 \x01(\v2\v.entpb.RoleR\x04role\"#\n" +
	"\x11DeleteRoleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xba\x01\n" +
	"\x0fListRoleRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12/\n" +
	"\x04view\x18\x03 \x01(\x0e2\x1b.entpb.ListRoleRequest.ViewR\x04view\":\n" +
	"\x04View\x12\x14\n" +
	"\x10VIEW_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05BASIC\x10\x01\x12\x11\n" +
	"\rWITH_EDGE_IDS\x10\x02\"d\n" +
	"\x10ListRoleResponse\x12(\n" +
	"\trole_list\x18\x01 \x03(\v2\v.entpb.RoleR\broleList\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"O\n" +
	"\x17BatchCreateRolesRequest\x124\n" +
	"\brequests\x18\x01 \x03(\v2\x18.entpb.CreateRoleRequestR\brequests\"=\n" +
	"\x18BatchCreateRolesResponse\x12!\n" +
	"\x05roles\x18\x01 \x03(\v2\v.entpb.RoleR\x05roles2\xdf\x02\n" +
	"\vPermService\x12/\n" +
	"\x06Create\x12\x18.entpb.CreatePermRequest\x1a\v.entpb.Perm\x12)\n" +
	"\x03Get\x12\x15.entpb.GetPermRequest\x1a\v.entpb.Perm\x12/\n" +
	"\x06Update\x12\x18.entpb.UpdatePermRequest\x1a\v.entpb.Perm\x12:\n" +
	"\x06Delete\x12\x18.entpb.DeletePermRequest\x1a\x16.google.protobuf.Empty\x127\n" +
	"\x04List\x12\x16.entpb.ListPermRequest\x1a\x17.entpb.ListPermResponse\x12N\n" +
	"\vBatchCreate\x12\x1e.entpb.BatchCreatePermsRequest\x1a\x1f.entpb.BatchCreatePermsResponse2\x9b\x03\n" +
	"\x10PermGroupService\x129\n" +
	"\x06Create\x12\x1d.entpb.CreatePermGroupRequest\x1a\x10.entpb.PermGroup\x123\n" +
	"\x03Get\x12\x1a.entpb.GetPermGroupRequest\x1a\x10.entpb.PermGroup\x129\n" +
	"\x06Update\x12\x1d.entpb.UpdatePermGroupRequest\x1a\x10.entpb.PermGroup\x12?\n" +
	"\x06Delete\x12\x1d.entpb.DeletePermGroupRequest\x1a\x16.google.protobuf.Empty\x12A\n" +
	"\x04List\x12\x1b.entpb.ListPermGroupRequest\x1a\x1c.entpb.ListPermGroupResponse\x12X\n" +
	"\vBatchCreate\x12#.entpb.BatchCreatePermGroupsRequest\x1a$.entpb.BatchCreatePermGroupsResponse2\xdf\x02\n" +
	"\vRoleService\x12/\n" +
	"\x06Create\x12\x18.entpb.CreateRoleRequest\x1a\v.entpb.Role\x12)\n" +
	"\x03Get\x12\x15.entpb.GetRoleRequest\x1a\v.entpb.Role\x12/\n" +
	"\x06Update\x12\x18.entpb.UpdateRoleRequest\x1a\v.entpb.Role\x12:\n" +
	"\x06Delete\x12\x18.entpb.DeleteRoleRequest\x1a\x16.google.protobuf.Empty\x127\n" +
	"\x04List\x12\x16.entpb.ListRoleRequest\x1a\x17.entpb.ListRoleResponse\x12N\n" +
	"\vBatchCreate\x12\x1e.entpb.BatchCreateRolesRequest\x1a\x1f.entpb.BatchCreateRolesResponseB9Z7github.com/longgggwww/hrm-ms-permission/ent/proto/entpbb\x06proto3"

var (
	file_entpb_entpb_proto_rawDescOnce sync.Once
	file_entpb_entpb_proto_rawDescData []byte
)

func file_entpb_entpb_proto_rawDescGZIP() []byte {
	file_entpb_entpb_proto_rawDescOnce.Do(func() {
		file_entpb_entpb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_entpb_entpb_proto_rawDesc), len(file_entpb_entpb_proto_rawDesc)))
	})
	return file_entpb_entpb_proto_rawDescData
}

var file_entpb_entpb_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_entpb_entpb_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_entpb_entpb_proto_goTypes = []any{
	(GetPermRequest_View)(0),              // 0: entpb.GetPermRequest.View
	(ListPermRequest_View)(0),             // 1: entpb.ListPermRequest.View
	(GetPermGroupRequest_View)(0),         // 2: entpb.GetPermGroupRequest.View
	(ListPermGroupRequest_View)(0),        // 3: entpb.ListPermGroupRequest.View
	(GetRoleRequest_View)(0),              // 4: entpb.GetRoleRequest.View
	(ListRoleRequest_View)(0),             // 5: entpb.ListRoleRequest.View
	(*Perm)(nil),                          // 6: entpb.Perm
	(*CreatePermRequest)(nil),             // 7: entpb.CreatePermRequest
	(*GetPermRequest)(nil),                // 8: entpb.GetPermRequest
	(*UpdatePermRequest)(nil),             // 9: entpb.UpdatePermRequest
	(*DeletePermRequest)(nil),             // 10: entpb.DeletePermRequest
	(*ListPermRequest)(nil),               // 11: entpb.ListPermRequest
	(*ListPermResponse)(nil),              // 12: entpb.ListPermResponse
	(*BatchCreatePermsRequest)(nil),       // 13: entpb.BatchCreatePermsRequest
	(*BatchCreatePermsResponse)(nil),      // 14: entpb.BatchCreatePermsResponse
	(*PermGroup)(nil),                     // 15: entpb.PermGroup
	(*CreatePermGroupRequest)(nil),        // 16: entpb.CreatePermGroupRequest
	(*GetPermGroupRequest)(nil),           // 17: entpb.GetPermGroupRequest
	(*UpdatePermGroupRequest)(nil),        // 18: entpb.UpdatePermGroupRequest
	(*DeletePermGroupRequest)(nil),        // 19: entpb.DeletePermGroupRequest
	(*ListPermGroupRequest)(nil),          // 20: entpb.ListPermGroupRequest
	(*ListPermGroupResponse)(nil),         // 21: entpb.ListPermGroupResponse
	(*BatchCreatePermGroupsRequest)(nil),  // 22: entpb.BatchCreatePermGroupsRequest
	(*BatchCreatePermGroupsResponse)(nil), // 23: entpb.BatchCreatePermGroupsResponse
	(*Role)(nil),                          // 24: entpb.Role
	(*CreateRoleRequest)(nil),             // 25: entpb.CreateRoleRequest
	(*GetRoleRequest)(nil),                // 26: entpb.GetRoleRequest
	(*UpdateRoleRequest)(nil),             // 27: entpb.UpdateRoleRequest
	(*DeleteRoleRequest)(nil),             // 28: entpb.DeleteRoleRequest
	(*ListRoleRequest)(nil),               // 29: entpb.ListRoleRequest
	(*ListRoleResponse)(nil),              // 30: entpb.ListRoleResponse
	(*BatchCreateRolesRequest)(nil),       // 31: entpb.BatchCreateRolesRequest
	(*BatchCreateRolesResponse)(nil),      // 32: entpb.BatchCreateRolesResponse
	(*wrapperspb.StringValue)(nil),        // 33: google.protobuf.StringValue
	(*emptypb.Empty)(nil),                 // 34: google.protobuf.Empty
}
var file_entpb_entpb_proto_depIdxs = []int32{
	33, // 0: entpb.Perm.description:type_name -> google.protobuf.StringValue
	15, // 1: entpb.Perm.group:type_name -> entpb.PermGroup
	24, // 2: entpb.Perm.roles:type_name -> entpb.Role
	6,  // 3: entpb.CreatePermRequest.perm:type_name -> entpb.Perm
	0,  // 4: entpb.GetPermRequest.view:type_name -> entpb.GetPermRequest.View
	6,  // 5: entpb.UpdatePermRequest.perm:type_name -> entpb.Perm
	1,  // 6: entpb.ListPermRequest.view:type_name -> entpb.ListPermRequest.View
	6,  // 7: entpb.ListPermResponse.perm_list:type_name -> entpb.Perm
	7,  // 8: entpb.BatchCreatePermsRequest.requests:type_name -> entpb.CreatePermRequest
	6,  // 9: entpb.BatchCreatePermsResponse.perms:type_name -> entpb.Perm
	6,  // 10: entpb.PermGroup.perms:type_name -> entpb.Perm
	15, // 11: entpb.CreatePermGroupRequest.perm_group:type_name -> entpb.PermGroup
	2,  // 12: entpb.GetPermGroupRequest.view:type_name -> entpb.GetPermGroupRequest.View
	15, // 13: entpb.UpdatePermGroupRequest.perm_group:type_name -> entpb.PermGroup
	3,  // 14: entpb.ListPermGroupRequest.view:type_name -> entpb.ListPermGroupRequest.View
	15, // 15: entpb.ListPermGroupResponse.perm_group_list:type_name -> entpb.PermGroup
	16, // 16: entpb.BatchCreatePermGroupsRequest.requests:type_name -> entpb.CreatePermGroupRequest
	15, // 17: entpb.BatchCreatePermGroupsResponse.perm_groups:type_name -> entpb.PermGroup
	33, // 18: entpb.Role.color:type_name -> google.protobuf.StringValue
	33, // 19: entpb.Role.description:type_name -> google.protobuf.StringValue
	6,  // 20: entpb.Role.perms:type_name -> entpb.Perm
	24, // 21: entpb.CreateRoleRequest.role:type_name -> entpb.Role
	4,  // 22: entpb.GetRoleRequest.view:type_name -> entpb.GetRoleRequest.View
	24, // 23: entpb.UpdateRoleRequest.role:type_name -> entpb.Role
	5,  // 24: entpb.ListRoleRequest.view:type_name -> entpb.ListRoleRequest.View
	24, // 25: entpb.ListRoleResponse.role_list:type_name -> entpb.Role
	25, // 26: entpb.BatchCreateRolesRequest.requests:type_name -> entpb.CreateRoleRequest
	24, // 27: entpb.BatchCreateRolesResponse.roles:type_name -> entpb.Role
	7,  // 28: entpb.PermService.Create:input_type -> entpb.CreatePermRequest
	8,  // 29: entpb.PermService.Get:input_type -> entpb.GetPermRequest
	9,  // 30: entpb.PermService.Update:input_type -> entpb.UpdatePermRequest
	10, // 31: entpb.PermService.Delete:input_type -> entpb.DeletePermRequest
	11, // 32: entpb.PermService.List:input_type -> entpb.ListPermRequest
	13, // 33: entpb.PermService.BatchCreate:input_type -> entpb.BatchCreatePermsRequest
	16, // 34: entpb.PermGroupService.Create:input_type -> entpb.CreatePermGroupRequest
	17, // 35: entpb.PermGroupService.Get:input_type -> entpb.GetPermGroupRequest
	18, // 36: entpb.PermGroupService.Update:input_type -> entpb.UpdatePermGroupRequest
	19, // 37: entpb.PermGroupService.Delete:input_type -> entpb.DeletePermGroupRequest
	20, // 38: entpb.PermGroupService.List:input_type -> entpb.ListPermGroupRequest
	22, // 39: entpb.PermGroupService.BatchCreate:input_type -> entpb.BatchCreatePermGroupsRequest
	25, // 40: entpb.RoleService.Create:input_type -> entpb.CreateRoleRequest
	26, // 41: entpb.RoleService.Get:input_type -> entpb.GetRoleRequest
	27, // 42: entpb.RoleService.Update:input_type -> entpb.UpdateRoleRequest
	28, // 43: entpb.RoleService.Delete:input_type -> entpb.DeleteRoleRequest
	29, // 44: entpb.RoleService.List:input_type -> entpb.ListRoleRequest
	31, // 45: entpb.RoleService.BatchCreate:input_type -> entpb.BatchCreateRolesRequest
	6,  // 46: entpb.PermService.Create:output_type -> entpb.Perm
	6,  // 47: entpb.PermService.Get:output_type -> entpb.Perm
	6,  // 48: entpb.PermService.Update:output_type -> entpb.Perm
	34, // 49: entpb.PermService.Delete:output_type -> google.protobuf.Empty
	12, // 50: entpb.PermService.List:output_type -> entpb.ListPermResponse
	14, // 51: entpb.PermService.BatchCreate:output_type -> entpb.BatchCreatePermsResponse
	15, // 52: entpb.PermGroupService.Create:output_type -> entpb.PermGroup
	15, // 53: entpb.PermGroupService.Get:output_type -> entpb.PermGroup
	15, // 54: entpb.PermGroupService.Update:output_type -> entpb.PermGroup
	34, // 55: entpb.PermGroupService.Delete:output_type -> google.protobuf.Empty
	21, // 56: entpb.PermGroupService.List:output_type -> entpb.ListPermGroupResponse
	23, // 57: entpb.PermGroupService.BatchCreate:output_type -> entpb.BatchCreatePermGroupsResponse
	24, // 58: entpb.RoleService.Create:output_type -> entpb.Role
	24, // 59: entpb.RoleService.Get:output_type -> entpb.Role
	24, // 60: entpb.RoleService.Update:output_type -> entpb.Role
	34, // 61: entpb.RoleService.Delete:output_type -> google.protobuf.Empty
	30, // 62: entpb.RoleService.List:output_type -> entpb.ListRoleResponse
	32, // 63: entpb.RoleService.BatchCreate:output_type -> entpb.BatchCreateRolesResponse
	46, // [46:64] is the sub-list for method output_type
	28, // [28:46] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_entpb_entpb_proto_init() }
func file_entpb_entpb_proto_init() {
	if File_entpb_entpb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entpb_entpb_proto_rawDesc), len(file_entpb_entpb_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_entpb_entpb_proto_goTypes,
		DependencyIndexes: file_entpb_entpb_proto_depIdxs,
		EnumInfos:         file_entpb_entpb_proto_enumTypes,
		MessageInfos:      file_entpb_entpb_proto_msgTypes,
	}.Build()
	File_entpb_entpb_proto = out.File
	file_entpb_entpb_proto_goTypes = nil
	file_entpb_entpb_proto_depIdxs = nil
}
