services:
  app:
    container_name: hrm-perm
    build:
      # dockerfile: Dockerfile
      dockerfile: Dockerfile.dev # for development
    ports:
      - "8080:8080"
      - "5000:5000"
    environment:
      GIN_MODE: ${GIN_MODE}
      DB_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASS}@postgres:5432/${POSTGRES_DB}?sslmode=disable
    volumes:
      - .:/app # for development
    depends_on:
      - postgres
    networks:
      - shared_network

  postgres:
    image: postgres:16-alpine
    container_name: hrm-perm-postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-"root"}
      POSTGRES_PASSWORD: ${POSTGRES_PASS:-"123456"}
      POSTGRES_DB: ${POSTGRES_DB:-"postgres"}
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - shared_network

volumes:
  data:
    name: hrm-perm-data

networks:
  shared_network:
    name: hrm-shared-network
