FROM golang:1.24-alpine AS base

WORKDIR /app

# Install necessary tools
RUN apk add --no-cache bash git curl && \
    go install github.com/air-verse/air@latest && \
    curl -sSf https://atlasgo.sh | sh

COPY go.mod go.sum ./

RUN go mod download

COPY . .

EXPOSE 5000 8080

CMD ["air"]