services:
  perm_app:
    container_name: hrm_perm
    build:
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000" # GRPC
      - "8080:8080"
    environment:
      GIN_MODE: ${GIN_MODE:-debug}
      DB_URL: ${DB_URL:-postgres://${DB_USER}:${DB_PASS}@perm_postgres:5432/${DB_NAME}?sslmode=disable}
      USER_SERVICE: ${USER_SERVICE:-user_app:8080}
    volumes:
      - .:/app
    depends_on:
      - perm_postgres
    networks:
      - shared_network

  perm_postgres:
    image: postgres:16-alpine
    container_name: hrm_perm_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-root}
      POSTGRES_PASSWORD: ${DB_PASS:-123456}
      POSTGRES_DB: ${DB_NAME:-postgres}
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - shared_network

volumes:
  data:
    name: hrm_perm_data

networks:
  shared_network:
    name: hrm_shared_network
    external: true
