services:
  app:
    container_name: hrm_perm_dev
    build:
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000" # GRPC
      - "8080:8080"
    environment:
      GIN_MODE: ${GIN_MODE}
      DB_URL: ${DB_URL:-postgres://${DB_USER}:${DB_PASS}@postgres:5432/${DB_NAME}?sslmode=disable}
    volumes:
      - .:/app
    depends_on:
      - postgres
    networks:
      - shared_network

  postgres:
    image: postgres:16-alpine
    container_name: hrm_perm_postgres_dev
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USER:-root}
      POSTGRES_PASSWORD: ${DB_PASS:-123456}
      POSTGRES_DB: ${DB_NAME:-postgres}
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - shared_network

volumes:
  data:
    name: hrm_perm_data_dev

networks:
  shared_network:
    name: hrm_shared_network_dev
