services:
  app:
    container_name: hrm-permission-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/${DB_NAME}
    # volumes:
    #   - .:/app
    depends_on:
      - db
      - kafka
      - redis

  db:
    image: postgres:16-alpine
    container_name: hrm-permission-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER:- root}
      POSTGRES_PASSWORD: ${DB_PASSWORD:- 123456}
      POSTGRES_DB: ${DB_NAME:- postgres}
    volumes:
      - data:/var/lib/postgresql/data

  kafka:
    image: bitnami/kafka:latest
    container_name: hrm-permission-kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: hrm-permission-zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  redis:
    image: redis:7-alpine
    container_name: hrm-permission-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  data:
    name: hrm-permission-data
