// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/longgggwww/hrm-ms-permission/internal/ent/eventstore"
	"github.com/longgggwww/hrm-ms-permission/internal/ent/predicate"
)

// EventStoreQuery is the builder for querying EventStore entities.
type EventStoreQuery struct {
	config
	ctx        *QueryContext
	order      []eventstore.OrderOption
	inters     []Interceptor
	predicates []predicate.EventStore
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the EventStoreQuery builder.
func (esq *EventStoreQuery) Where(ps ...predicate.EventStore) *EventStoreQuery {
	esq.predicates = append(esq.predicates, ps...)
	return esq
}

// Limit the number of records to be returned by this query.
func (esq *EventStoreQuery) Limit(limit int) *EventStoreQuery {
	esq.ctx.Limit = &limit
	return esq
}

// Offset to start from.
func (esq *EventStoreQuery) Offset(offset int) *EventStoreQuery {
	esq.ctx.Offset = &offset
	return esq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (esq *EventStoreQuery) Unique(unique bool) *EventStoreQuery {
	esq.ctx.Unique = &unique
	return esq
}

// Order specifies how the records should be ordered.
func (esq *EventStoreQuery) Order(o ...eventstore.OrderOption) *EventStoreQuery {
	esq.order = append(esq.order, o...)
	return esq
}

// First returns the first EventStore entity from the query.
// Returns a *NotFoundError when no EventStore was found.
func (esq *EventStoreQuery) First(ctx context.Context) (*EventStore, error) {
	nodes, err := esq.Limit(1).All(setContextOp(ctx, esq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{eventstore.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (esq *EventStoreQuery) FirstX(ctx context.Context) *EventStore {
	node, err := esq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first EventStore ID from the query.
// Returns a *NotFoundError when no EventStore ID was found.
func (esq *EventStoreQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = esq.Limit(1).IDs(setContextOp(ctx, esq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{eventstore.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (esq *EventStoreQuery) FirstIDX(ctx context.Context) int {
	id, err := esq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single EventStore entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one EventStore entity is found.
// Returns a *NotFoundError when no EventStore entities are found.
func (esq *EventStoreQuery) Only(ctx context.Context) (*EventStore, error) {
	nodes, err := esq.Limit(2).All(setContextOp(ctx, esq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{eventstore.Label}
	default:
		return nil, &NotSingularError{eventstore.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (esq *EventStoreQuery) OnlyX(ctx context.Context) *EventStore {
	node, err := esq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only EventStore ID in the query.
// Returns a *NotSingularError when more than one EventStore ID is found.
// Returns a *NotFoundError when no entities are found.
func (esq *EventStoreQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = esq.Limit(2).IDs(setContextOp(ctx, esq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{eventstore.Label}
	default:
		err = &NotSingularError{eventstore.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (esq *EventStoreQuery) OnlyIDX(ctx context.Context) int {
	id, err := esq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of EventStores.
func (esq *EventStoreQuery) All(ctx context.Context) ([]*EventStore, error) {
	ctx = setContextOp(ctx, esq.ctx, ent.OpQueryAll)
	if err := esq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*EventStore, *EventStoreQuery]()
	return withInterceptors[[]*EventStore](ctx, esq, qr, esq.inters)
}

// AllX is like All, but panics if an error occurs.
func (esq *EventStoreQuery) AllX(ctx context.Context) []*EventStore {
	nodes, err := esq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of EventStore IDs.
func (esq *EventStoreQuery) IDs(ctx context.Context) (ids []int, err error) {
	if esq.ctx.Unique == nil && esq.path != nil {
		esq.Unique(true)
	}
	ctx = setContextOp(ctx, esq.ctx, ent.OpQueryIDs)
	if err = esq.Select(eventstore.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (esq *EventStoreQuery) IDsX(ctx context.Context) []int {
	ids, err := esq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (esq *EventStoreQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, esq.ctx, ent.OpQueryCount)
	if err := esq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, esq, querierCount[*EventStoreQuery](), esq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (esq *EventStoreQuery) CountX(ctx context.Context) int {
	count, err := esq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (esq *EventStoreQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, esq.ctx, ent.OpQueryExist)
	switch _, err := esq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (esq *EventStoreQuery) ExistX(ctx context.Context) bool {
	exist, err := esq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the EventStoreQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (esq *EventStoreQuery) Clone() *EventStoreQuery {
	if esq == nil {
		return nil
	}
	return &EventStoreQuery{
		config:     esq.config,
		ctx:        esq.ctx.Clone(),
		order:      append([]eventstore.OrderOption{}, esq.order...),
		inters:     append([]Interceptor{}, esq.inters...),
		predicates: append([]predicate.EventStore{}, esq.predicates...),
		// clone intermediate query.
		sql:  esq.sql.Clone(),
		path: esq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		EventID string `json:"event_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.EventStore.Query().
//		GroupBy(eventstore.FieldEventID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (esq *EventStoreQuery) GroupBy(field string, fields ...string) *EventStoreGroupBy {
	esq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &EventStoreGroupBy{build: esq}
	grbuild.flds = &esq.ctx.Fields
	grbuild.label = eventstore.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		EventID string `json:"event_id,omitempty"`
//	}
//
//	client.EventStore.Query().
//		Select(eventstore.FieldEventID).
//		Scan(ctx, &v)
func (esq *EventStoreQuery) Select(fields ...string) *EventStoreSelect {
	esq.ctx.Fields = append(esq.ctx.Fields, fields...)
	sbuild := &EventStoreSelect{EventStoreQuery: esq}
	sbuild.label = eventstore.Label
	sbuild.flds, sbuild.scan = &esq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a EventStoreSelect configured with the given aggregations.
func (esq *EventStoreQuery) Aggregate(fns ...AggregateFunc) *EventStoreSelect {
	return esq.Select().Aggregate(fns...)
}

func (esq *EventStoreQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range esq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, esq); err != nil {
				return err
			}
		}
	}
	for _, f := range esq.ctx.Fields {
		if !eventstore.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if esq.path != nil {
		prev, err := esq.path(ctx)
		if err != nil {
			return err
		}
		esq.sql = prev
	}
	return nil
}

func (esq *EventStoreQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*EventStore, error) {
	var (
		nodes = []*EventStore{}
		_spec = esq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*EventStore).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &EventStore{config: esq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, esq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (esq *EventStoreQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := esq.querySpec()
	_spec.Node.Columns = esq.ctx.Fields
	if len(esq.ctx.Fields) > 0 {
		_spec.Unique = esq.ctx.Unique != nil && *esq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, esq.driver, _spec)
}

func (esq *EventStoreQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(eventstore.Table, eventstore.Columns, sqlgraph.NewFieldSpec(eventstore.FieldID, field.TypeInt))
	_spec.From = esq.sql
	if unique := esq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if esq.path != nil {
		_spec.Unique = true
	}
	if fields := esq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, eventstore.FieldID)
		for i := range fields {
			if fields[i] != eventstore.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := esq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := esq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := esq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := esq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (esq *EventStoreQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(esq.driver.Dialect())
	t1 := builder.Table(eventstore.Table)
	columns := esq.ctx.Fields
	if len(columns) == 0 {
		columns = eventstore.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if esq.sql != nil {
		selector = esq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if esq.ctx.Unique != nil && *esq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range esq.predicates {
		p(selector)
	}
	for _, p := range esq.order {
		p(selector)
	}
	if offset := esq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := esq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// EventStoreGroupBy is the group-by builder for EventStore entities.
type EventStoreGroupBy struct {
	selector
	build *EventStoreQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (esgb *EventStoreGroupBy) Aggregate(fns ...AggregateFunc) *EventStoreGroupBy {
	esgb.fns = append(esgb.fns, fns...)
	return esgb
}

// Scan applies the selector query and scans the result into the given value.
func (esgb *EventStoreGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, esgb.build.ctx, ent.OpQueryGroupBy)
	if err := esgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EventStoreQuery, *EventStoreGroupBy](ctx, esgb.build, esgb, esgb.build.inters, v)
}

func (esgb *EventStoreGroupBy) sqlScan(ctx context.Context, root *EventStoreQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(esgb.fns))
	for _, fn := range esgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*esgb.flds)+len(esgb.fns))
		for _, f := range *esgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*esgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := esgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// EventStoreSelect is the builder for selecting fields of EventStore entities.
type EventStoreSelect struct {
	*EventStoreQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ess *EventStoreSelect) Aggregate(fns ...AggregateFunc) *EventStoreSelect {
	ess.fns = append(ess.fns, fns...)
	return ess
}

// Scan applies the selector query and scans the result into the given value.
func (ess *EventStoreSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ess.ctx, ent.OpQuerySelect)
	if err := ess.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EventStoreQuery, *EventStoreSelect](ctx, ess.EventStoreQuery, ess, ess.inters, v)
}

func (ess *EventStoreSelect) sqlScan(ctx context.Context, root *EventStoreQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ess.fns))
	for _, fn := range ess.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ess.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ess.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
