// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/longgggwww/hrm-ms-permission/ent/perm"
	"github.com/longgggwww/hrm-ms-permission/ent/permgroup"
)

// PermGroupCreate is the builder for creating a PermGroup entity.
type PermGroupCreate struct {
	config
	mutation *PermGroupMutation
	hooks    []Hook
}

// SetCode sets the "code" field.
func (pgc *PermGroupCreate) SetCode(s string) *PermGroupCreate {
	pgc.mutation.SetCode(s)
	return pgc
}

// SetName sets the "name" field.
func (pgc *PermGroupCreate) SetName(s string) *PermGroupCreate {
	pgc.mutation.SetName(s)
	return pgc
}

// AddPermIDs adds the "perms" edge to the Perm entity by IDs.
func (pgc *PermGroupCreate) AddPermIDs(ids ...int) *PermGroupCreate {
	pgc.mutation.AddPermIDs(ids...)
	return pgc
}

// AddPerms adds the "perms" edges to the Perm entity.
func (pgc *PermGroupCreate) AddPerms(p ...*Perm) *PermGroupCreate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pgc.AddPermIDs(ids...)
}

// Mutation returns the PermGroupMutation object of the builder.
func (pgc *PermGroupCreate) Mutation() *PermGroupMutation {
	return pgc.mutation
}

// Save creates the PermGroup in the database.
func (pgc *PermGroupCreate) Save(ctx context.Context) (*PermGroup, error) {
	return withHooks(ctx, pgc.sqlSave, pgc.mutation, pgc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pgc *PermGroupCreate) SaveX(ctx context.Context) *PermGroup {
	v, err := pgc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pgc *PermGroupCreate) Exec(ctx context.Context) error {
	_, err := pgc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pgc *PermGroupCreate) ExecX(ctx context.Context) {
	if err := pgc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pgc *PermGroupCreate) check() error {
	if _, ok := pgc.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "PermGroup.code"`)}
	}
	if _, ok := pgc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "PermGroup.name"`)}
	}
	return nil
}

func (pgc *PermGroupCreate) sqlSave(ctx context.Context) (*PermGroup, error) {
	if err := pgc.check(); err != nil {
		return nil, err
	}
	_node, _spec := pgc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pgc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	pgc.mutation.id = &_node.ID
	pgc.mutation.done = true
	return _node, nil
}

func (pgc *PermGroupCreate) createSpec() (*PermGroup, *sqlgraph.CreateSpec) {
	var (
		_node = &PermGroup{config: pgc.config}
		_spec = sqlgraph.NewCreateSpec(permgroup.Table, sqlgraph.NewFieldSpec(permgroup.FieldID, field.TypeInt))
	)
	if value, ok := pgc.mutation.Code(); ok {
		_spec.SetField(permgroup.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := pgc.mutation.Name(); ok {
		_spec.SetField(permgroup.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if nodes := pgc.mutation.PermsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   permgroup.PermsTable,
			Columns: []string{permgroup.PermsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(perm.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PermGroupCreateBulk is the builder for creating many PermGroup entities in bulk.
type PermGroupCreateBulk struct {
	config
	err      error
	builders []*PermGroupCreate
}

// Save creates the PermGroup entities in the database.
func (pgcb *PermGroupCreateBulk) Save(ctx context.Context) ([]*PermGroup, error) {
	if pgcb.err != nil {
		return nil, pgcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(pgcb.builders))
	nodes := make([]*PermGroup, len(pgcb.builders))
	mutators := make([]Mutator, len(pgcb.builders))
	for i := range pgcb.builders {
		func(i int, root context.Context) {
			builder := pgcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PermGroupMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pgcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pgcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pgcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pgcb *PermGroupCreateBulk) SaveX(ctx context.Context) []*PermGroup {
	v, err := pgcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pgcb *PermGroupCreateBulk) Exec(ctx context.Context) error {
	_, err := pgcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pgcb *PermGroupCreateBulk) ExecX(ctx context.Context) {
	if err := pgcb.Exec(ctx); err != nil {
		panic(err)
	}
}
