// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/longgggwwww/hrm-ms-permission/ent/perm"
	"github.com/longgggwwww/hrm-ms-permission/ent/permgroup"
)

// PermGroupCreate is the builder for creating a PermGroup entity.
type PermGroupCreate struct {
	config
	mutation *PermGroupMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCode sets the "code" field.
func (pgc *PermGroupCreate) SetCode(s string) *PermGroupCreate {
	pgc.mutation.SetCode(s)
	return pgc
}

// SetName sets the "name" field.
func (pgc *PermGroupCreate) SetName(s string) *PermGroupCreate {
	pgc.mutation.SetName(s)
	return pgc
}

// SetID sets the "id" field.
func (pgc *PermGroupCreate) SetID(u uuid.UUID) *PermGroupCreate {
	pgc.mutation.SetID(u)
	return pgc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (pgc *PermGroupCreate) SetNillableID(u *uuid.UUID) *PermGroupCreate {
	if u != nil {
		pgc.SetID(*u)
	}
	return pgc
}

// AddPermIDs adds the "perms" edge to the Perm entity by IDs.
func (pgc *PermGroupCreate) AddPermIDs(ids ...uuid.UUID) *PermGroupCreate {
	pgc.mutation.AddPermIDs(ids...)
	return pgc
}

// AddPerms adds the "perms" edges to the Perm entity.
func (pgc *PermGroupCreate) AddPerms(p ...*Perm) *PermGroupCreate {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pgc.AddPermIDs(ids...)
}

// Mutation returns the PermGroupMutation object of the builder.
func (pgc *PermGroupCreate) Mutation() *PermGroupMutation {
	return pgc.mutation
}

// Save creates the PermGroup in the database.
func (pgc *PermGroupCreate) Save(ctx context.Context) (*PermGroup, error) {
	pgc.defaults()
	return withHooks(ctx, pgc.sqlSave, pgc.mutation, pgc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pgc *PermGroupCreate) SaveX(ctx context.Context) *PermGroup {
	v, err := pgc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pgc *PermGroupCreate) Exec(ctx context.Context) error {
	_, err := pgc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pgc *PermGroupCreate) ExecX(ctx context.Context) {
	if err := pgc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pgc *PermGroupCreate) defaults() {
	if _, ok := pgc.mutation.ID(); !ok {
		v := permgroup.DefaultID()
		pgc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pgc *PermGroupCreate) check() error {
	if _, ok := pgc.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "PermGroup.code"`)}
	}
	if _, ok := pgc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "PermGroup.name"`)}
	}
	if v, ok := pgc.mutation.Name(); ok {
		if err := permgroup.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PermGroup.name": %w`, err)}
		}
	}
	return nil
}

func (pgc *PermGroupCreate) sqlSave(ctx context.Context) (*PermGroup, error) {
	if err := pgc.check(); err != nil {
		return nil, err
	}
	_node, _spec := pgc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pgc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	pgc.mutation.id = &_node.ID
	pgc.mutation.done = true
	return _node, nil
}

func (pgc *PermGroupCreate) createSpec() (*PermGroup, *sqlgraph.CreateSpec) {
	var (
		_node = &PermGroup{config: pgc.config}
		_spec = sqlgraph.NewCreateSpec(permgroup.Table, sqlgraph.NewFieldSpec(permgroup.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = pgc.conflict
	if id, ok := pgc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := pgc.mutation.Code(); ok {
		_spec.SetField(permgroup.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := pgc.mutation.Name(); ok {
		_spec.SetField(permgroup.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if nodes := pgc.mutation.PermsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   permgroup.PermsTable,
			Columns: []string{permgroup.PermsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(perm.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PermGroup.Create().
//		SetCode(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PermGroupUpsert) {
//			SetCode(v+v).
//		}).
//		Exec(ctx)
func (pgc *PermGroupCreate) OnConflict(opts ...sql.ConflictOption) *PermGroupUpsertOne {
	pgc.conflict = opts
	return &PermGroupUpsertOne{
		create: pgc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PermGroup.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (pgc *PermGroupCreate) OnConflictColumns(columns ...string) *PermGroupUpsertOne {
	pgc.conflict = append(pgc.conflict, sql.ConflictColumns(columns...))
	return &PermGroupUpsertOne{
		create: pgc,
	}
}

type (
	// PermGroupUpsertOne is the builder for "upsert"-ing
	//  one PermGroup node.
	PermGroupUpsertOne struct {
		create *PermGroupCreate
	}

	// PermGroupUpsert is the "OnConflict" setter.
	PermGroupUpsert struct {
		*sql.UpdateSet
	}
)

// SetCode sets the "code" field.
func (u *PermGroupUpsert) SetCode(v string) *PermGroupUpsert {
	u.Set(permgroup.FieldCode, v)
	return u
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *PermGroupUpsert) UpdateCode() *PermGroupUpsert {
	u.SetExcluded(permgroup.FieldCode)
	return u
}

// SetName sets the "name" field.
func (u *PermGroupUpsert) SetName(v string) *PermGroupUpsert {
	u.Set(permgroup.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PermGroupUpsert) UpdateName() *PermGroupUpsert {
	u.SetExcluded(permgroup.FieldName)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.PermGroup.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(permgroup.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PermGroupUpsertOne) UpdateNewValues() *PermGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(permgroup.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PermGroup.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PermGroupUpsertOne) Ignore() *PermGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PermGroupUpsertOne) DoNothing() *PermGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PermGroupCreate.OnConflict
// documentation for more info.
func (u *PermGroupUpsertOne) Update(set func(*PermGroupUpsert)) *PermGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PermGroupUpsert{UpdateSet: update})
	}))
	return u
}

// SetCode sets the "code" field.
func (u *PermGroupUpsertOne) SetCode(v string) *PermGroupUpsertOne {
	return u.Update(func(s *PermGroupUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *PermGroupUpsertOne) UpdateCode() *PermGroupUpsertOne {
	return u.Update(func(s *PermGroupUpsert) {
		s.UpdateCode()
	})
}

// SetName sets the "name" field.
func (u *PermGroupUpsertOne) SetName(v string) *PermGroupUpsertOne {
	return u.Update(func(s *PermGroupUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PermGroupUpsertOne) UpdateName() *PermGroupUpsertOne {
	return u.Update(func(s *PermGroupUpsert) {
		s.UpdateName()
	})
}

// Exec executes the query.
func (u *PermGroupUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PermGroupCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PermGroupUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PermGroupUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: PermGroupUpsertOne.ID is not supported by MySQL driver. Use PermGroupUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PermGroupUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PermGroupCreateBulk is the builder for creating many PermGroup entities in bulk.
type PermGroupCreateBulk struct {
	config
	err      error
	builders []*PermGroupCreate
	conflict []sql.ConflictOption
}

// Save creates the PermGroup entities in the database.
func (pgcb *PermGroupCreateBulk) Save(ctx context.Context) ([]*PermGroup, error) {
	if pgcb.err != nil {
		return nil, pgcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(pgcb.builders))
	nodes := make([]*PermGroup, len(pgcb.builders))
	mutators := make([]Mutator, len(pgcb.builders))
	for i := range pgcb.builders {
		func(i int, root context.Context) {
			builder := pgcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PermGroupMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pgcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = pgcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pgcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pgcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pgcb *PermGroupCreateBulk) SaveX(ctx context.Context) []*PermGroup {
	v, err := pgcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pgcb *PermGroupCreateBulk) Exec(ctx context.Context) error {
	_, err := pgcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pgcb *PermGroupCreateBulk) ExecX(ctx context.Context) {
	if err := pgcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PermGroup.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PermGroupUpsert) {
//			SetCode(v+v).
//		}).
//		Exec(ctx)
func (pgcb *PermGroupCreateBulk) OnConflict(opts ...sql.ConflictOption) *PermGroupUpsertBulk {
	pgcb.conflict = opts
	return &PermGroupUpsertBulk{
		create: pgcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PermGroup.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (pgcb *PermGroupCreateBulk) OnConflictColumns(columns ...string) *PermGroupUpsertBulk {
	pgcb.conflict = append(pgcb.conflict, sql.ConflictColumns(columns...))
	return &PermGroupUpsertBulk{
		create: pgcb,
	}
}

// PermGroupUpsertBulk is the builder for "upsert"-ing
// a bulk of PermGroup nodes.
type PermGroupUpsertBulk struct {
	create *PermGroupCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PermGroup.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(permgroup.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PermGroupUpsertBulk) UpdateNewValues() *PermGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(permgroup.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PermGroup.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PermGroupUpsertBulk) Ignore() *PermGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PermGroupUpsertBulk) DoNothing() *PermGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PermGroupCreateBulk.OnConflict
// documentation for more info.
func (u *PermGroupUpsertBulk) Update(set func(*PermGroupUpsert)) *PermGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PermGroupUpsert{UpdateSet: update})
	}))
	return u
}

// SetCode sets the "code" field.
func (u *PermGroupUpsertBulk) SetCode(v string) *PermGroupUpsertBulk {
	return u.Update(func(s *PermGroupUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *PermGroupUpsertBulk) UpdateCode() *PermGroupUpsertBulk {
	return u.Update(func(s *PermGroupUpsert) {
		s.UpdateCode()
	})
}

// SetName sets the "name" field.
func (u *PermGroupUpsertBulk) SetName(v string) *PermGroupUpsertBulk {
	return u.Update(func(s *PermGroupUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PermGroupUpsertBulk) UpdateName() *PermGroupUpsertBulk {
	return u.Update(func(s *PermGroupUpsert) {
		s.UpdateName()
	})
}

// Exec executes the query.
func (u *PermGroupUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PermGroupCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PermGroupCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PermGroupUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
