// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/longgggwwww/hrm-ms-permission/ent/perm"
	"github.com/longgggwwww/hrm-ms-permission/ent/permgroup"
	"github.com/longgggwwww/hrm-ms-permission/ent/role"
	"github.com/longgggwwww/hrm-ms-permission/ent/schema"
	"github.com/longgggwwww/hrm-ms-permission/ent/userperm"
	"github.com/longgggwwww/hrm-ms-permission/ent/userrole"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	permFields := schema.Perm{}.Fields()
	_ = permFields
	// permDescName is the schema descriptor for name field.
	permDescName := permFields[2].Descriptor()
	// perm.NameValidator is a validator for the "name" field. It is called by the builders before save.
	perm.NameValidator = permDescName.Validators[0].(func(string) error)
	// permDescID is the schema descriptor for id field.
	permDescID := permFields[0].Descriptor()
	// perm.DefaultID holds the default value on creation for the id field.
	perm.DefaultID = permDescID.Default.(func() uuid.UUID)
	permgroupFields := schema.PermGroup{}.Fields()
	_ = permgroupFields
	// permgroupDescName is the schema descriptor for name field.
	permgroupDescName := permgroupFields[2].Descriptor()
	// permgroup.NameValidator is a validator for the "name" field. It is called by the builders before save.
	permgroup.NameValidator = permgroupDescName.Validators[0].(func(string) error)
	// permgroupDescID is the schema descriptor for id field.
	permgroupDescID := permgroupFields[0].Descriptor()
	// permgroup.DefaultID holds the default value on creation for the id field.
	permgroup.DefaultID = permgroupDescID.Default.(func() uuid.UUID)
	roleFields := schema.Role{}.Fields()
	_ = roleFields
	// roleDescName is the schema descriptor for name field.
	roleDescName := roleFields[2].Descriptor()
	// role.NameValidator is a validator for the "name" field. It is called by the builders before save.
	role.NameValidator = roleDescName.Validators[0].(func(string) error)
	// roleDescID is the schema descriptor for id field.
	roleDescID := roleFields[0].Descriptor()
	// role.DefaultID holds the default value on creation for the id field.
	role.DefaultID = roleDescID.Default.(func() uuid.UUID)
	userpermFields := schema.UserPerm{}.Fields()
	_ = userpermFields
	// userpermDescUserID is the schema descriptor for user_id field.
	userpermDescUserID := userpermFields[0].Descriptor()
	// userperm.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	userperm.UserIDValidator = userpermDescUserID.Validators[0].(func(string) error)
	// userpermDescCreatedAt is the schema descriptor for created_at field.
	userpermDescCreatedAt := userpermFields[2].Descriptor()
	// userperm.DefaultCreatedAt holds the default value on creation for the created_at field.
	userperm.DefaultCreatedAt = userpermDescCreatedAt.Default.(func() time.Time)
	// userpermDescUpdatedAt is the schema descriptor for updated_at field.
	userpermDescUpdatedAt := userpermFields[3].Descriptor()
	// userperm.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	userperm.DefaultUpdatedAt = userpermDescUpdatedAt.Default.(func() time.Time)
	// userperm.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	userperm.UpdateDefaultUpdatedAt = userpermDescUpdatedAt.UpdateDefault.(func() time.Time)
	userroleFields := schema.UserRole{}.Fields()
	_ = userroleFields
	// userroleDescUserID is the schema descriptor for user_id field.
	userroleDescUserID := userroleFields[1].Descriptor()
	// userrole.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	userrole.UserIDValidator = userroleDescUserID.Validators[0].(func(string) error)
	// userroleDescCreatedAt is the schema descriptor for created_at field.
	userroleDescCreatedAt := userroleFields[3].Descriptor()
	// userrole.DefaultCreatedAt holds the default value on creation for the created_at field.
	userrole.DefaultCreatedAt = userroleDescCreatedAt.Default.(func() time.Time)
	// userroleDescUpdatedAt is the schema descriptor for updated_at field.
	userroleDescUpdatedAt := userroleFields[4].Descriptor()
	// userrole.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	userrole.DefaultUpdatedAt = userroleDescUpdatedAt.Default.(func() time.Time)
	// userrole.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	userrole.UpdateDefaultUpdatedAt = userroleDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userroleDescID is the schema descriptor for id field.
	userroleDescID := userroleFields[0].Descriptor()
	// userrole.DefaultID holds the default value on creation for the id field.
	userrole.DefaultID = userroleDescID.Default.(func() uuid.UUID)
}
