-- Create "roles" table
CREATE TABLE "roles" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying NOT NULL, "color" character varying NULL, "description" character varying NULL, PRIMARY KEY ("id"));
-- Create index "roles_name_key" to table: "roles"
CREATE UNIQUE INDEX "roles_name_key" ON "roles" ("name");
-- Create "role_perms" table
CREATE TABLE "role_perms" ("role_id" bigint NOT NULL, "perm_id" bigint NOT NULL, PRIMARY KEY ("role_id", "perm_id"), CONSTRAINT "role_perms_perm_id" FOREIGN KEY ("perm_id") REFERENCES "perms" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "role_perms_role_id" FOREIGN KEY ("role_id") REFERENCES "roles" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
