-- Create "perm_groups" table
CREATE TABLE "perm_groups" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "code" character varying NOT NULL, "name" character varying NOT NULL, PRIMARY KEY ("id"));
-- Create index "perm_groups_code_key" to table: "perm_groups"
CREATE UNIQUE INDEX "perm_groups_code_key" ON "perm_groups" ("code");
-- Create "perms" table
CREATE TABLE "perms" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "code" character varying NOT NULL, "name" character varying NOT NULL, "description" character varying NULL, "perm_group" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "perms_perm_groups_group" FOREIGN KEY ("perm_group") REFERENCES "perm_groups" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- Create index "perms_code_key" to table: "perms"
CREATE UNIQUE INDEX "perms_code_key" ON "perms" ("code");
