// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Perm is the predicate function for perm builders.
type Perm func(*sql.Selector)

// PermGroup is the predicate function for permgroup builders.
type PermGroup func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// UserRole is the predicate function for userrole builders.
type UserRole func(*sql.Selector)
